/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppTodayRouteImport } from './routes/app.today'
import { Route as AppTasksRouteImport } from './routes/app.tasks'
import { Route as AppStatsRouteImport } from './routes/app.stats'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppHabitsRouteImport } from './routes/app.habits'
import { Route as AppCalendarRouteImport } from './routes/app.calendar'

const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppTodayRoute = AppTodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => AppRoute,
} as any)
const AppTasksRoute = AppTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AppRoute,
} as any)
const AppStatsRoute = AppStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppHabitsRoute = AppHabitsRouteImport.update({
  id: '/habits',
  path: '/habits',
  getParentRoute: () => AppRoute,
} as any)
const AppCalendarRoute = AppCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/calendar': typeof AppCalendarRoute
  '/app/habits': typeof AppHabitsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/stats': typeof AppStatsRoute
  '/app/tasks': typeof AppTasksRoute
  '/app/today': typeof AppTodayRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/habits': typeof AppHabitsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/stats': typeof AppStatsRoute
  '/app/tasks': typeof AppTasksRoute
  '/app/today': typeof AppTodayRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/calendar': typeof AppCalendarRoute
  '/app/habits': typeof AppHabitsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/stats': typeof AppStatsRoute
  '/app/tasks': typeof AppTasksRoute
  '/app/today': typeof AppTodayRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/calendar'
    | '/app/habits'
    | '/app/settings'
    | '/app/stats'
    | '/app/tasks'
    | '/app/today'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app/calendar'
    | '/app/habits'
    | '/app/settings'
    | '/app/stats'
    | '/app/tasks'
    | '/app/today'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/calendar'
    | '/app/habits'
    | '/app/settings'
    | '/app/stats'
    | '/app/tasks'
    | '/app/today'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/today': {
      id: '/app/today'
      path: '/today'
      fullPath: '/app/today'
      preLoaderRoute: typeof AppTodayRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/tasks': {
      id: '/app/tasks'
      path: '/tasks'
      fullPath: '/app/tasks'
      preLoaderRoute: typeof AppTasksRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/stats': {
      id: '/app/stats'
      path: '/stats'
      fullPath: '/app/stats'
      preLoaderRoute: typeof AppStatsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/habits': {
      id: '/app/habits'
      path: '/habits'
      fullPath: '/app/habits'
      preLoaderRoute: typeof AppHabitsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/calendar': {
      id: '/app/calendar'
      path: '/calendar'
      fullPath: '/app/calendar'
      preLoaderRoute: typeof AppCalendarRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppCalendarRoute: typeof AppCalendarRoute
  AppHabitsRoute: typeof AppHabitsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppStatsRoute: typeof AppStatsRoute
  AppTasksRoute: typeof AppTasksRoute
  AppTodayRoute: typeof AppTodayRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCalendarRoute: AppCalendarRoute,
  AppHabitsRoute: AppHabitsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppStatsRoute: AppStatsRoute,
  AppTasksRoute: AppTasksRoute,
  AppTodayRoute: AppTodayRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.jsx'
import type { startInstance } from './start.js'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
